name: Docker
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: cloud-tools

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build images
        run: |
          GOOGLE_CLOUD_CLI_IMAGE_TAG="$(make print-google-cloud-cli-image-tag)"
          docker buildx build --build-arg GOOGLE_CLOUD_CLI_IMAGE_TAG=${GOOGLE_CLOUD_CLI_IMAGE_TAG} --load . --tag $IMAGE_NAME:latest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push images to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          # Change all uppercase to lowercase.
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo IMAGE_ID=$IMAGE_ID
          GOOGLE_CLOUD_CLI_IMAGE_TAG="$(make print-google-cloud-cli-image-tag)"
          docker buildx build --build-arg GOOGLE_CLOUD_CLI_IMAGE_TAG=${GOOGLE_CLOUD_CLI_IMAGE_TAG} --push . --platform "linux/amd64,linux/arm64" \
            --tag $IMAGE_ID:latest \
